#
- name: rabbitmq - set main configuration file
  template:
    src: "rabbitmq.config.j2"
    dest: "/etc/rabbitmq/rabbitmq.config"
    owner: "root"
    group: "root"
    mode: 0644

- name: enable plugins
  rabbitmq_plugin:
    names=rabbitmq_management

- name: add rabbitmq user and set privileges
  rabbitmq_user:
    user=rabbit
    password=rabbit
    vhost=/
    node=rabbit
    configure_priv=.*
    read_priv=.*
    write_priv=.*
    state=present
    tags=administrator
    force=yes

- name: rabbitmq - restart (forced)
  service:
    name: "rabbitmq-server"
    state: "restarted"
    enabled: "yes"
